# Generated by Django 4.2.4 on 2023-12-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('size', models.CharField(max_length=50)),
                ('min_sillas', models.PositiveIntegerField()),
                ('max_sillas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('sillas', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
