# Generated by Django 4.2.4 on 2023-09-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_rename_nombre_espacio_nombre_spc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prod', models.CharField(max_length=50)),
                ('espacio_id', models.BigIntegerField()),
            ],
        ),
    ]
