# Generated by Django 4.2.4 on 2023-09-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0003_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='espacio_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
