# Generated by Django 4.2.4 on 2023-09-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0005_alter_producto_espacio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
