# Generated by Django 4.2.4 on 2023-09-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0007_orden_producto_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='orden',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='espacios.orden'),
        ),
    ]
