# Generated by Django 4.2.4 on 2023-09-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0011_rename_orden_key_producto_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='orden',
        ),
    ]
