# Generated by Django 4.2.4 on 2023-09-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0013_productoorden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoorden',
            old_name='cantidad',
            new_name='cantidad1',
        ),
    ]
