# Generated by Django 4.2.4 on 2023-09-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0014_rename_cantidad_productoorden_cantidad1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoorden',
            old_name='cantidad1',
            new_name='cantidad',
        ),
    ]
