# Generated by Django 4.2.4 on 2023-09-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0015_rename_cantidad1_productoorden_cantidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoOrden',
            new_name='ProductOrden',
        ),
    ]
