# Generated by Django 4.2.4 on 2023-09-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0017_rename_productorden_productoorden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoOrden',
        ),
    ]
