# Generated by Django 4.2.4 on 2023-09-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0019_productoorden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoOrden',
        ),
    ]
