# Generated by Django 4.2.4 on 2023-09-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0022_rename_productoorden_productorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='productos',
            field=models.ManyToManyField(through='espacios.ProductOrden', to='espacios.producto'),
        ),
    ]
