# Generated by Django 4.2.4 on 2023-09-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0023_orden_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='productos',
            new_name='producto',
        ),
    ]
