# Generated by Django 4.2.4 on 2023-09-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0024_rename_productos_orden_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='producto',
        ),
    ]
