# Generated by Django 4.2.4 on 2023-09-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0026_orden_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorden',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='productorden',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='productorden',
            name='producto',
        ),
        migrations.AddField(
            model_name='productorden',
            name='test',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='productos',
            field=models.ManyToManyField(to='espacios.producto'),
        ),
    ]
