# Generated by Django 4.2.4 on 2023-09-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0029_delete_productorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='productos',
            field=models.ManyToManyField(to='espacios.producto'),
        ),
        migrations.DeleteModel(
            name='nOrden',
        ),
    ]
