# Generated by Django 4.2.4 on 2023-09-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0032_delete_norden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
