# Generated by Django 4.2.4 on 2023-09-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0034_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='productos',
        ),
    ]
