# Generated by Django 4.2.4 on 2023-09-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0036_orden_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
