# Generated by Django 4.2.4 on 2023-09-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0041_orden_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenproducto',
            old_name='orden_id',
            new_name='orden',
        ),
        migrations.RenameField(
            model_name='ordenproducto',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
