# Generated by Django 4.2.4 on 2023-10-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0042_rename_orden_id_ordenproducto_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_prod',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
