# Generated by Django 4.2.4 on 2023-10-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0048_espacio_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espacio',
            old_name='admin',
            new_name='owner',
        ),
    ]
