# Generated by Django 4.2.4 on 2023-10-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0049_rename_admin_espacio_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espacio',
            name='owner',
        ),
    ]
